[package]
name = "photomatic"
version = "0.1.0"
edition = "2021"

[dependencies]
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winapi = { version = "0.3", features = ["combaseapi", "objbase", "winuser", "wingdi", "commctrl"] }
rusqlite = { version = "0.40.1", features = ["bundled", "chrono"] }
rusqlite_migration = "2.6.0"
chrono = { version = "0.4.45", features = ["serde"] }
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }

[build-dependencies]
embed-manifest = "1"

[profile.release]
strip = true
