name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build release
        run: cargo build --release --verbose

      - name: Package
        shell: pwsh
        run: |
          $zipName = "photomatic-$env:GITHUB_REF_NAME-windows-x64.zip"
          Compress-Archive -Path target\release\photomatic.exe -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
